name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-12

    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=16.0,name=iPhone 14 Pro']
          scheme: ['WidgetKitExample', 'WeatherWidgetExtension', 'EditableIntent', 'EditableWidgetExtension']

    steps:
    - uses: actions/checkout@v2
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_14.0.app
    - name: Build
      run: xcodebuild clean build -scheme "${{ matrix.scheme }}" -destination "${{ matrix.destination }}"
